version: "2"
plugins:
    brakeman:
      enabled: true
    bundler-audit:
      enabled: true
    csslint:
      enabled: true
    flog:
      enabled: true
      config:
        score_threshold: 20.0
    markdownlint:
      enabled: true
    reek:
      enabled: true
    rubocop:
      enabled: true
      channel: "rubocop-0-49"
exclude_patterns:
  - bin/
  - config/
  - db/
  - vendor/
  - tmp/