version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.1.0

commands:
  wait-for-datastores:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:2.7.2-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: salaries-circleci
          PGPASSWORD: password
          REDIS_URL: redis://127.0.0.1:6379/
          SMARDO_NAMESPACE: /v2
      - image: circleci/postgres:11.8
        environment:
          POSTGRES_USER: salaries-circleci
          POSTGRES_DB: salaries_test
          POSTGRES_PASSWORD: password
      - image: circleci/redis:6.0.8-alpine
    environment:
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: 12.18.3
      - node/install-packages:
          pkg-manager: yarn
      - wait-for-datastores
      - run: bin/rails db:create db:schema:load
      - ruby/rspec-test
      - run:
          name: Run Standard RB check
          command: bundle exec standardrb --format progress


workflows:
  check_and_test:
    jobs:
      - test
